 image:
   file: .gitpod.Dockerfile
tasks:
  - command: ./minifab up


#tasks:
#  - before: pip3 install -r requirements.txt
#    command: redis-server --daemonize yes && pyenv shell 3.8.13 && echo "Welcome to your Workspace"
#vscode:
#  extensions:
#    - ms-python.python